/* Generated By:JJTree: Do not edit this line. ASTAtTranform.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package org.openntf.domino.tests.rpr.formula;

public
class ASTAtTranform extends SimpleNode {
  public ASTAtTranform(int id) {
    super(id);
  }

  public ASTAtTranform(AtFormulaParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=d08c10f53cbe3e6f0bbecd2b484b65ca (do not edit this line) */
