/* Generated By:JJTree: Do not edit this line. ASTAtFor.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package org.openntf.domino.tests.rpr.formula;

public
class ASTAtFor extends SimpleNode {
  public ASTAtFor(int id) {
    super(id);
  }

  public ASTAtFor(AtFormulaParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=0429a9ba8223f5b11632aa09b6327538 (do not edit this line) */
