/* Generated By:JJTree: Do not edit this line. ASTAtIf.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package org.openntf.domino.tests.rpr.formula;

public
class ASTAtIf extends SimpleNode {
  public ASTAtIf(int id) {
    super(id);
  }

  public ASTAtIf(AtFormulaParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=b5c9fab831bb73f4e873e76edb6677cd (do not edit this line) */
