/* Generated By:JJTree: Do not edit this line. ASTIntValue.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package org.openntf.domino.tests.rpr.formula;

public
class ASTIntValue extends SimpleNode {
  public ASTIntValue(int id) {
    super(id);
  }

  public ASTIntValue(AtFormulaParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=d47c9c9dc55ea8e6756e4ee70d38e888 (do not edit this line) */
