/* Generated By:JJTree: Do not edit this line. ASTNumericValue.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package org.openntf.domino.tests.rpr.formula;

public
class ASTNumericValue extends SimpleNode {
  public ASTNumericValue(int id) {
    super(id);
  }

  public ASTNumericValue(AtFormulaParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=68ae75fef7bd2dd6ba5e909ccefff3bb (do not edit this line) */
