/* Generated By:JJTree: Do not edit this line. ASTOpCmp.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package org.openntf.domino.tests.rpr.formula;

public
class ASTOpCmp extends SimpleNode {
  public ASTOpCmp(int id) {
    super(id);
  }

  public ASTOpCmp(AtFormulaParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=aab9e730bbbf40c1135c6d6ef3d9284a (do not edit this line) */
