/* Generated By:JJTree: Do not edit this line. ASTOpAdd.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package org.openntf.domino.tests.rpr.formula;

public
class ASTOpAdd extends SimpleNode {
  public ASTOpAdd(int id) {
    super(id);
  }

  public ASTOpAdd(AtFormulaParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=5a86f08d17735e9cb55166b4e2c6bc0f (do not edit this line) */
