/* Generated By:JJTree: Do not edit this line. ASTSetEnvironment.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package org.openntf.domino.tests.rpr.formula;

public
class ASTSetEnvironment extends SimpleNode {
  public ASTSetEnvironment(int id) {
    super(id);
  }

  public ASTSetEnvironment(AtFormulaParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=1f7a9a4f108491b8597e24ed3f55bb9f (do not edit this line) */
