/* Generated By:JJTree: Do not edit this line. ASTSelect.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package org.openntf.domino.tests.rpr.formula;

public
class ASTSelect extends SimpleNode {
  public ASTSelect(int id) {
    super(id);
  }

  public ASTSelect(AtFormulaParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=ecde0a7b8e20f238d96fa623d3dbc99f (do not edit this line) */
