/* Generated By:JJTree: Do not edit this line. ASTUnaryNeg.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package org.openntf.domino.tests.rpr.formula;

public
class ASTUnaryNeg extends SimpleNode {
  public ASTUnaryNeg(int id) {
    super(id);
  }

  public ASTUnaryNeg(AtFormulaParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=c486b73379b46fa8dc47c809abd7db83 (do not edit this line) */
