/* Generated By:JJTree: Do not edit this line. ASTValueDate.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package org.openntf.domino.tests.rpr.formula;

import java.util.Date;

public class ASTValueDate extends SimpleNode {
	Date value;

	// TODO: Do not split Date&Keyword
	public ASTValueDate(final int id) {
		super(id);
	}

	public ASTValueDate(final AtFormulaParser p, final int id) {
		super(p, id);
	}

	public void parseDate(final String image) {
		value = parser.getFormatter().parseDate(image.substring(1, image.length() - 1));
	}

	@Override
	public String toString() {
		return super.toString() + ": " + value;
	}

	@Override
	public Value evaluate(final FormulaContext ctx) {
		return new Value(value);
	}
}
/* JavaCC - OriginalChecksum=a57e37d317a3579029482f8b9b11308a (do not edit this line) */
