/* Generated By:JJTree&JavaCC: Do not edit this line. AtFormulaParserConstants.java */
package org.openntf.domino.tests.rpr.formula;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface AtFormulaParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int Date = 1;
  /** RegularExpression Id. */
  int Function_Keyword = 2;
  /** RegularExpression Id. */
  int OSubscript = 3;
  /** RegularExpression Id. */
  int CSubscript = 4;
  /** RegularExpression Id. */
  int EOS = 5;
  /** RegularExpression Id. */
  int OParen = 6;
  /** RegularExpression Id. */
  int CParen = 7;
  /** RegularExpression Id. */
  int Assign = 8;
  /** RegularExpression Id. */
  int BoolNot = 9;
  /** RegularExpression Id. */
  int KW_DEFAULT = 10;
  /** RegularExpression Id. */
  int KW_ENVIRONMENT = 11;
  /** RegularExpression Id. */
  int KW_FIELD = 12;
  /** RegularExpression Id. */
  int KW_REM = 13;
  /** RegularExpression Id. */
  int KW_SELECT = 14;
  /** RegularExpression Id. */
  int At_do = 15;
  /** RegularExpression Id. */
  int At_doWhile = 16;
  /** RegularExpression Id. */
  int At_for = 17;
  /** RegularExpression Id. */
  int At_if = 18;
  /** RegularExpression Id. */
  int At_iferror = 19;
  /** RegularExpression Id. */
  int At_transform = 20;
  /** RegularExpression Id. */
  int At_other = 21;
  /** RegularExpression Id. */
  int ListConcat = 22;
  /** RegularExpression Id. */
  int MultOps = 23;
  /** RegularExpression Id. */
  int OpMul = 24;
  /** RegularExpression Id. */
  int OpMulP = 25;
  /** RegularExpression Id. */
  int OpDiv = 26;
  /** RegularExpression Id. */
  int OpDivP = 27;
  /** RegularExpression Id. */
  int OpPlus = 28;
  /** RegularExpression Id. */
  int OpPlusP = 29;
  /** RegularExpression Id. */
  int OpMinus = 30;
  /** RegularExpression Id. */
  int OpMinusP = 31;
  /** RegularExpression Id. */
  int CmpOps = 32;
  /** RegularExpression Id. */
  int CmpEqual = 33;
  /** RegularExpression Id. */
  int CmpEqualP = 34;
  /** RegularExpression Id. */
  int CmpNE = 35;
  /** RegularExpression Id. */
  int CmpNEP = 36;
  /** RegularExpression Id. */
  int CmpLT = 37;
  /** RegularExpression Id. */
  int CmpLTP = 38;
  /** RegularExpression Id. */
  int CmpGT = 39;
  /** RegularExpression Id. */
  int CmpGTP = 40;
  /** RegularExpression Id. */
  int CmpLTE = 41;
  /** RegularExpression Id. */
  int CmpLTEP = 42;
  /** RegularExpression Id. */
  int CmpGTE = 43;
  /** RegularExpression Id. */
  int CmpGTEP = 44;
  /** RegularExpression Id. */
  int BoolAnd = 45;
  /** RegularExpression Id. */
  int BoolOr = 46;
  /** RegularExpression Id. */
  int NumDoubleUS = 47;
  /** RegularExpression Id. */
  int NumDoubleDE = 48;
  /** RegularExpression Id. */
  int NumInteger = 49;
  /** RegularExpression Id. */
  int Exponent = 50;
  /** RegularExpression Id. */
  int String1 = 51;
  /** RegularExpression Id. */
  int String2 = 52;
  /** RegularExpression Id. */
  int Identifier = 53;
  /** RegularExpression Id. */
  int Letter = 54;
  /** RegularExpression Id. */
  int Digit = 55;

  /** Lexical state. */
  int DEFAULT = 0;
  /** Lexical state. */
  int SUBSCRIPT = 1;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "<Date>",
    "<Function_Keyword>",
    "\"[\"",
    "\"]\"",
    "\";\"",
    "\"(\"",
    "\")\"",
    "\":=\"",
    "\"!\"",
    "\"DEFAULT\"",
    "\"ENVIRONMENT\"",
    "\"FIELD\"",
    "\"REM\"",
    "\"SELECT\"",
    "\"@do\"",
    "\"@doWhile\"",
    "\"@for\"",
    "\"@if\"",
    "\"@iferror\"",
    "\"@transform\"",
    "<At_other>",
    "\":\"",
    "<MultOps>",
    "\"*\"",
    "\"**\"",
    "\"/\"",
    "\"*/\"",
    "\"+\"",
    "\"*+\"",
    "\"-\"",
    "\"*-\"",
    "<CmpOps>",
    "\"=\"",
    "\"*=\"",
    "<CmpNE>",
    "\"*<>\"",
    "\"<\"",
    "\"*<\"",
    "\">\"",
    "\"*>\"",
    "\"<=\"",
    "\"*<=\"",
    "\">=\"",
    "\"*>=\"",
    "\"&\"",
    "\"|\"",
    "<NumDoubleUS>",
    "<NumDoubleDE>",
    "<NumInteger>",
    "<Exponent>",
    "<String1>",
    "<String2>",
    "<Identifier>",
    "<Letter>",
    "<Digit>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\r\\n\"",
  };

}
