/* Generated By:JJTree&JavaCC: Do not edit this line. AtFormulaParser.java */
package org.openntf.domino.tests.rpr.formula;

import java.util.ArrayList;
import java.util.Collections;
import java.util.Comparator;
import java.util.List;

import org.openntf.domino.formula.AtFunction;
import org.openntf.domino.formula.AtFunctionFactory;
import org.openntf.domino.thread.DominoThread;
import org.openntf.domino.utils.Factory;

public class PrintFunctionSet extends TestRunnerStdIn {
	public static void main(final String[] args) {
		DominoThread thread = new DominoThread(new PrintFunctionSet(), "My thread");
		thread.start();
	}

	public PrintFunctionSet() {
		// whatever you might want to do in your constructor, but stay away from Domino objects
	}

	@Override
	public void run() {
		try {
			System.out.println("Currently supported functions");
			List<AtFunction> funcs = new ArrayList<AtFunction>();
			funcs.addAll(AtFunctionFactory.getInstance().getFunctions().values());

			Collections.sort(funcs, new Comparator<AtFunction>() {
				@Override
				public int compare(final AtFunction o1, final AtFunction o2) {
					return o1.toString().compareTo(o2.toString());
				}
			});
			for (AtFunction func : funcs) {
				System.out.println(func);
			}
		} catch (Exception e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
		Factory.terminate();
		System.out.println(Factory.dumpCounters(true));
	}
}
