/* Generated By:JJTree&JavaCC: Do not edit this line. AtFormulaParser.java */
package org.openntf.domino.tests.rpr.formula;

import org.openntf.domino.tests.rpr.formula.eval.DefaultOperators;
import org.openntf.domino.tests.rpr.formula.eval.Value;
import org.openntf.domino.tests.rpr.formula.parse.AtFormulaParser;
import org.openntf.domino.tests.rpr.formula.parse.ParseException;
import org.openntf.domino.tests.rpr.formula.parse.SimpleNode;
import org.openntf.domino.tests.rpr.formula.parse.TokenMgrError;

public class TestRunner {

	public static void main(final String[] args) throws ParseException, TokenMgrError {
		AtFormulaParser parser = new AtFormulaParser(System.in);
		parser.init(new DominoFormatter(), new DefaultOperators());
		System.out.println("Please type a Lotus domino @formula. Quit with CTRL+Z:");
		SimpleNode n = parser.Parse();
		n.dump("");
		System.out.println("Evaluating");
		Value v = n.evaluate(null);
		for (int i = 0; i < v.size(); i++) {
			System.out.println("[" + i + "]: " + v.get(i));
		}
		System.out.println("Thank you.");

	}

}
