/* Generated By:JJTree: Do not edit this line. SimpleNode.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package org.openntf.domino.tests.rpr.formula;

public abstract class TreeNode extends SimpleNode {
	protected Node children[];

	/**
	 * @param p
	 * @param i
	 */
	public TreeNode(final AtFormulaParser p, final int i) {
		super(p, i);
		// TODO Auto-generated constructor stub
	}

	/**
	 * @param i
	 */
	public TreeNode(final int i) {
		super(i);
	}

	@Override
	public void jjtAddChild(final Node n, final int i) {
		if (children == null) {
			children = new Node[i + 1];
		} else if (i >= children.length) {
			Node c[] = new Node[i + 1];
			System.arraycopy(children, 0, c, 0, children.length);
			children = c;
		}
		children[i] = n;
	}

	@Override
	public Node jjtGetChild(final int i) {
		return children[i];
	}

	@Override
	public int jjtGetNumChildren() {
		return (children == null) ? 0 : children.length;
	}

}

/* JavaCC - OriginalChecksum=3dbb27fb2c89a6b3bb4f903355a329f0 (do not edit this line) */
