/* Generated By:JJTree: Do not edit this line. ASTAtDoWhile.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package org.openntf.domino.tests.rpr.formula.parse;

import org.openntf.domino.tests.rpr.formula.eval.FormulaContext;
import org.openntf.domino.tests.rpr.formula.eval.ValueHolder;

public class ASTAtDoWhile extends SimpleNode {
	public ASTAtDoWhile(final int id) {
		super(id);
	}

	public ASTAtDoWhile(final AtFormulaParser p, final int id) {
		super(p, id);
	}

	/**
	 * AtDoWhile returns always TRUE, as in the formula online help described
	 * 
	 * @throws EvaluateException
	 */
	@Override
	public ValueHolder evaluate(final FormulaContext ctx) throws EvaluateException {
		ValueHolder ret = null;
		do {
			for (int i = 0; i < jjtGetNumChildren(); ++i) {
				ret = jjtGetChild(i).evaluate(ctx);
			}
		} while (ret != null && ret.isTrue());

		return new ValueHolder(1); // returns always TRUE
	}

	public void toFormula(final StringBuilder sb) {
		sb.append("@DoWhile");
		appendParams(sb);
	}
}
/* JavaCC - OriginalChecksum=8e076d4573c126d678818b398f5e2cc2 (do not edit this line) */
