/* Generated By:JJTree: Do not edit this line. ASTAtIf.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package org.openntf.domino.tests.rpr.formula.parse;

import org.openntf.domino.tests.rpr.formula.eval.FormulaContext;
import org.openntf.domino.tests.rpr.formula.eval.Value;

class ASTAtIf extends SimpleNode {
	public ASTAtIf(final int id) {
		super(id);
	}

	public ASTAtIf(final AtFormulaParser p, final int id) {
		super(p, id);
	}

	@Override
	public Value evaluate(final FormulaContext ctx) {
		Value nIf;
		int i = 0;
		nIf = jjtGetChild(i++).evaluate(ctx);

		while (i < jjtGetNumChildren()) {
			if (nIf.isTrue()) {
				return jjtGetChild(i++).evaluate(ctx);
			} else {
				i++;
			}
			nIf = jjtGetChild(i++).evaluate(ctx);
		}

		return nIf; // returns always TRUE
	}
}
/* JavaCC - OriginalChecksum=3cf8886130c7d437d3d41d680ca0966f (do not edit this line) */
