/* Generated By:JJTree: Do not edit this line. ASTAtDo.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package org.openntf.domino.tests.rpr.formula.parse;

import org.openntf.domino.tests.rpr.formula.eval.FormulaContext;
import org.openntf.domino.tests.rpr.formula.eval.Value;

class ASTAtDo extends SimpleNode {
	public ASTAtDo(final int id) {
		super(id);
	}

	public ASTAtDo(final AtFormulaParser p, final int id) {
		super(p, id);
	}

	@Override
	public Value evaluate(final FormulaContext ctx) {
		Value ret = null;
		for (int i = 0; i < jjtGetNumChildren(); ++i) {
			ret = jjtGetChild(i).evaluate(ctx);
		}
		return ret;
	}
}
/* JavaCC - OriginalChecksum=3715ddf69e3be17452e7e4c207eb9b56 (do not edit this line) */
