/* Generated By:JJTree: Do not edit this line. ASTAtIfError.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package org.openntf.domino.tests.rpr.formula.parse;

import org.openntf.domino.tests.rpr.formula.eval.FormulaContext;
import org.openntf.domino.tests.rpr.formula.eval.Value;

public class ASTAtIfError extends SimpleNode {
	public ASTAtIfError(final int id) {
		super(id);
	}

	public ASTAtIfError(final AtFormulaParser p, final int id) {
		super(p, id);
	}

	@Override
	public Value evaluate(final FormulaContext ctx) {
		try {
			jjtGetChild(0).evaluate(ctx);
		} catch (RuntimeException ex) {
			if (jjtGetNumChildren() == 2) {
				return jjtGetChild(0).evaluate(ctx);
			}
		}
		return new Value("");
	}
}
/* JavaCC - OriginalChecksum=2989baa74781f053fff71f4e53ea4135 (do not edit this line) */
