/* Generated By:JJTree: Do not edit this line. ASTSelect.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package org.openntf.domino.tests.rpr.formula.parse;

import org.openntf.domino.tests.rpr.formula.eval.FormulaContext;
import org.openntf.domino.tests.rpr.formula.eval.ValueHolder;

public class ASTSelect extends SimpleNode {
	public ASTSelect(final int id) {
		super(id);
	}

	public ASTSelect(final AtFormulaParser p, final int id) {
		super(p, id);
	}

	@Override
	public ValueHolder evaluate(final FormulaContext ctx) {
		throw new UnsupportedOperationException("SELECT keyword not yet supported. (What should it do?)");
	}

	@Override
	public void toFormula(final StringBuilder sb) {
		sb.append("SELECT");
		children[0].toFormula(sb);
	}
}
/* JavaCC - OriginalChecksum=057c2d20fb3de924f1a585cd1da530a3 (do not edit this line) */
