/* Generated By:JJTree: Do not edit this line. ASTValueString.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package org.openntf.domino.tests.rpr.formula.parse;

import org.openntf.domino.tests.rpr.formula.eval.FormulaContext;
import org.openntf.domino.tests.rpr.formula.eval.Value;

public class ASTValueString extends SimpleNode {
	String value;

	public ASTValueString(final int id) {
		super(id);
	}

	public ASTValueString(final AtFormulaParser p, final int id) {
		super(p, id);
	}

	public void parseString(final String image, final char c) {
		value = image;
	}

	@Override
	public String toString() {
		return super.toString() + ": " + value;
	}

	@Override
	public Value evaluate(final FormulaContext ctx) {
		return new Value(value);
	}

}
/* JavaCC - OriginalChecksum=b093634abe91991ac4fe1c236b97b93b (do not edit this line) */
