/* Generated By:JJTree: Do not edit this line. ASTAtFor.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
/*
 * © Copyright FOCONIS AG, 2014
 * 
 * Licensed under the Apache License, Version 2.0 (the "License"); 
 * you may not use this file except in compliance with the License. 
 * You may obtain a copy of the License at:
 * 
 * http://www.apache.org/licenses/LICENSE-2.0
 * 
 * Unless required by applicable law or agreed to in writing, software 
 * distributed under the License is distributed on an "AS IS" BASIS, 
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or 
 * implied. See the License for the specific language governing 
 * permissions and limitations under the License.
 */
package org.openntf.domino.formula.ast;

import org.openntf.domino.formula.AtFormulaParser;
import org.openntf.domino.formula.EvaluateException;
import org.openntf.domino.formula.FormulaContext;
import org.openntf.domino.formula.ValueHolder;

public class ASTAtFor extends SimpleNode {
	public ASTAtFor(final int id) {
		super(id);
	}

	public ASTAtFor(final AtFormulaParser p, final int id) {
		super(p, id);
	}

	@Override
	public ValueHolder evaluate(final FormulaContext ctx) throws EvaluateException {
		Node init = jjtGetChild(0);
		Node condition = jjtGetChild(1);
		Node increment = jjtGetChild(2);

		init.evaluate(ctx);
		while (condition.evaluate(ctx).isTrue()) {
			// execute statements
			for (int i = 3; i < jjtGetNumChildren(); ++i) {
				jjtGetChild(i).evaluate(ctx);
			}
			increment.evaluate(ctx);
		}

		return new ValueHolder(1); // returns always TRUE
	}

	public void toFormula(final StringBuilder sb) {
		sb.append("@For");
		appendParams(sb);
	}
}
/* JavaCC - OriginalChecksum=f70d2e6a39964b2d6bee287bd8bf7aca (do not edit this line) */
