/* Generated By:JJTree: Do not edit this line. ASTAtIsError.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
/*
 * © Copyright FOCONIS AG, 2014
 * 
 * Licensed under the Apache License, Version 2.0 (the "License"); 
 * you may not use this file except in compliance with the License. 
 * You may obtain a copy of the License at:
 * 
 * http://www.apache.org/licenses/LICENSE-2.0
 * 
 * Unless required by applicable law or agreed to in writing, software 
 * distributed under the License is distributed on an "AS IS" BASIS, 
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or 
 * implied. See the License for the specific language governing 
 * permissions and limitations under the License.
 * 
 */
package org.openntf.domino.formula.ast;

import java.util.Set;

import org.openntf.domino.formula.FormulaContext;
import org.openntf.domino.formula.FormulaReturnException;
import org.openntf.domino.formula.ValueHolder;
import org.openntf.domino.formula.ValueHolder.DataType;
import org.openntf.domino.formula.parse.AtFormulaParserImpl;

/**
 * Implements the {@literal @}IsError function
 * 
 * @author Roland Praml, Foconis AG
 * 
 */
public class ASTAtIsError extends SimpleNode {

	public ASTAtIsError(final AtFormulaParserImpl p, final int id) {
		super(p, id);
	}

	/**
	 * Returns {@link FormulaContext#TRUE ctx.TRUE} if the Value's Datatype = DataType.ERROR
	 */
	@Override
	public ValueHolder evaluate(final FormulaContext ctx) throws FormulaReturnException {

		ValueHolder ret = children[0].evaluate(ctx);
		if (ret.dataType == DataType.ERROR)
			return ctx.TRUE;
		return ctx.FALSE;

	}

	/*
	 * (non-Javadoc)
	 * @see org.openntf.domino.formula.ASTNode#toFormula(java.lang.StringBuilder)
	 */
	public void toFormula(final StringBuilder sb) {
		sb.append("@IsError");
		appendParams(sb);

	}

	/*
	 * (non-Javadoc)
	 * @see org.openntf.domino.formula.ast.SimpleNode#analyzeThis(java.util.Set, java.util.Set, java.util.Set, java.util.Set)
	 */
	@Override
	protected void analyzeThis(final Set<String> readFields, final Set<String> modifiedFields, final Set<String> variables,
			final Set<String> functions) {
		functions.add("@iserror");
	}
}
/* JavaCC - OriginalChecksum=b3d48e49618a861ba4c9d1737e4b2b5f (do not edit this line) */
