/* Generated By:JJTree: Do not edit this line. ASTExtendedFunction.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package org.openntf.domino.formula.ast;

import org.openntf.domino.formula.AtFormulaParserImpl;
import org.openntf.domino.formula.FormulaContext;
import org.openntf.domino.formula.FormulaReturnException;
import org.openntf.domino.formula.ValueHolder;

public class ASTExtendedFunction extends SimpleNode {
	public ASTExtendedFunction(final int id) {
		super(id);
	}

	public ASTExtendedFunction(final AtFormulaParserImpl p, final int id) {
		super(p, id);
	}

	public void init(final String image) {
		// TODO Auto-generated method stub

	}

	public void toFormula(final StringBuilder sb) {
		// TODO Auto-generated method stub

	}

	@Override
	public ValueHolder evaluate(final FormulaContext ctx) throws FormulaReturnException {
		// TODO Auto-generated method stub
		return null;
	}

}
/* JavaCC - OriginalChecksum=0bef6e155cd93f4bed8a7902e8dc69c4 (do not edit this line) */
