/* Generated By:JavaCC: Do not edit this line. AtFormulaParserImplTreeConstants.java Version 5.0 */
package org.openntf.domino.formula.ast;

import org.openntf.domino.formula.*;

public interface AtFormulaParserImplTreeConstants
{
  public int JJTATDO = 0;
  public int JJTVOID = 1;
  public int JJTATCONCAT = 2;
  public int JJTNORMALTEXT = 3;
  public int JJTEXTENDEDINCLUDE = 4;
  public int JJTEXTENDEDFUNCTION = 5;
  public int JJTASSIGNMENT = 6;
  public int JJTSELECT = 7;
  public int JJTEXTENDEDFUNCTIONDEF = 8;
  public int JJTEXTENDEDPARAMETER = 9;
  public int JJTEXTENDEDVARIABLE = 10;
  public int JJTOPERATOR = 11;
  public int JJTVALUELIST = 12;
  public int JJTSUBSCRIPT = 13;
  public int JJTATDOWHILE = 14;
  public int JJTATFOR = 15;
  public int JJTATIF = 16;
  public int JJTATIFERROR = 17;
  public int JJTATTRANSFORM = 18;
  public int JJTATSORT = 19;
  public int JJTATEVAL = 20;
  public int JJTATFOCEVAL = 21;
  public int JJTATTEXT = 22;
  public int JJTATRETURN = 23;
  public int JJTATISERROR = 24;
  public int JJTFUNCTION = 25;
  public int JJTVALUEDATEORKW = 26;
  public int JJTVALUESTRING = 27;
  public int JJTVALUEDOUBLE = 28;
  public int JJTVALUEINT = 29;
  public int JJTGETVARIABLE = 30;


  public String[] jjtNodeName = {
    "AtDo",
    "void",
    "AtConCat",
    "NormalText",
    "ExtendedInclude",
    "ExtendedFunction",
    "Assignment",
    "Select",
    "ExtendedFunctionDef",
    "ExtendedParameter",
    "ExtendedVariable",
    "Operator",
    "ValueList",
    "Subscript",
    "AtDoWhile",
    "AtFor",
    "AtIf",
    "AtIfError",
    "AtTransform",
    "AtSort",
    "AtEval",
    "AtFocEval",
    "AtText",
    "AtReturn",
    "AtIsError",
    "Function",
    "ValueDateOrKW",
    "ValueString",
    "ValueDouble",
    "ValueInt",
    "GetVariable",
  };
}
/* JavaCC - OriginalChecksum=a7d01a8b947d3fe52ea0ef597de47e9f (do not edit this line) */
