/* Generated By:JavaCC: Do not edit this line. AtFormulaParserTreeConstants.java Version 5.0 */
/*
 * © Copyright FOCONIS AG, 2014
 * 
 * Licensed under the Apache License, Version 2.0 (the "License"); 
 * you may not use this file except in compliance with the License. 
 * You may obtain a copy of the License at:
 * 
 * http://www.apache.org/licenses/LICENSE-2.0
 * 
 * Unless required by applicable law or agreed to in writing, software 
 * distributed under the License is distributed on an "AS IS" BASIS, 
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or 
 * implied. See the License for the specific language governing 
 * permissions and limitations under the License.
 * 
 */
package org.openntf.domino.formula.ast;


public interface AtFormulaParserTreeConstants {
	public int JJTATDO = 0;
	public int JJTVOID = 1;
	public int JJTASSIGNMENT = 2;
	public int JJTSELECT = 3;
	public int JJTOPERATOR = 4;
	public int JJTVALUELIST = 5;
	public int JJTSUBSCRIPT = 6;
	public int JJTATDOWHILE = 7;
	public int JJTATFOR = 8;
	public int JJTATIF = 9;
	public int JJTATIFERROR = 10;
	public int JJTATTRANFORM = 11;
	public int JJTFUNCTION = 12;
	public int JJTVALUEDATEORKW = 13;
	public int JJTVALUESTRING = 14;
	public int JJTVALUEDOUBLE = 15;
	public int JJTVALUELONG = 16;
	public int JJTGETVARIABLE = 17;

	public String[] jjtNodeName = { "AtDo", "void", "Assignment", "Select", "Operator", "ValueList", "Subscript", "AtDoWhile", "AtFor",
			"AtIf", "AtIfError", "AtTranform", "Function", "ValueDateOrKW", "ValueString", "ValueDouble", "ValueLong", "GetVariable", };
}
/* JavaCC - OriginalChecksum=637942eea622ef22d33a1c955776778a (do not edit this line) */
