/* Generated By:JavaCC: Do not edit this line. AtFormulaParserImplTreeConstants.java Version 5.0 */
package org.openntf.domino.formula.ast;

import org.openntf.domino.formula.parse.*;

public interface AtFormulaParserImplTreeConstants
{
  public int JJTATDO = 0;
  public int JJTVOID = 1;
  public int JJTATCONCAT = 2;
  public int JJTFOCPARAM = 3;
  public int JJTFOCNORMALTEXT = 4;
  public int JJTUSERDEFINEDINCLUDE = 5;
  public int JJTUSERDEFINEDFUNCTION = 6;
  public int JJTASSIGNMENT = 7;
  public int JJTSELECT = 8;
  public int JJTUSERDEFINEDFUNCTIONDEF = 9;
  public int JJTUSERDEFINEDFUNCTIONPARAMETER = 10;
  public int JJTUSERDEFINEDFUNCTIONVARIABLE = 11;
  public int JJTOPERATOR = 12;
  public int JJTVALUELIST = 13;
  public int JJTSUBSCRIPT = 14;
  public int JJTATDOWHILE = 15;
  public int JJTATFOR = 16;
  public int JJTATIF = 17;
  public int JJTATIFERROR = 18;
  public int JJTATTRANSFORM = 19;
  public int JJTATSORT = 20;
  public int JJTATEVAL = 21;
  public int JJTATFOCEVAL = 22;
  public int JJTATTEXT = 23;
  public int JJTATRETURN = 24;
  public int JJTATISERROR = 25;
  public int JJTFUNCTION = 26;
  public int JJTVALUEDATEORKW = 27;
  public int JJTVALUESTRING = 28;
  public int JJTVALUEDOUBLE = 29;
  public int JJTVALUEINT = 30;
  public int JJTGETVARIABLE = 31;


  public String[] jjtNodeName = {
    "AtDo",
    "void",
    "AtConCat",
    "FocParam",
    "FocNormalText",
    "UserDefinedInclude",
    "UserDefinedFunction",
    "Assignment",
    "Select",
    "UserDefinedFunctionDef",
    "UserDefinedFunctionParameter",
    "UserDefinedFunctionVariable",
    "Operator",
    "ValueList",
    "Subscript",
    "AtDoWhile",
    "AtFor",
    "AtIf",
    "AtIfError",
    "AtTransform",
    "AtSort",
    "AtEval",
    "AtFocEval",
    "AtText",
    "AtReturn",
    "AtIsError",
    "Function",
    "ValueDateOrKW",
    "ValueString",
    "ValueDouble",
    "ValueInt",
    "GetVariable",
  };
}
/* JavaCC - OriginalChecksum=a05c7d2066f7c4df44fee89a4667fe6c (do not edit this line) */
