package org.openntf.domino.nsfdata.structs.cd;

public enum FieldType {
	ERROR, NUMBER, TIME, RICH_TEXT, AUTHORS, READERS, NAMES, KEYWORDS, TEXT, SECTION, PASSWORD, FORMULA, TIMEZONE, UNUSED13, UNUSED14,
	UNUSED15, UNUSED16, UNUSED17, COLORCTL
}