/* Generated By:JJTree: Do not edit this line. ASTAtIsUnavailable.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package org.openntf.domino.formula.ast;

import org.openntf.domino.formula.FormulaContext;
import org.openntf.domino.formula.FormulaReturnException;
import org.openntf.domino.formula.ValueHolder;
import org.openntf.domino.formula.parse.AtFormulaParserImpl;

public class ASTAtIsUnavailable extends ASTAtIsAvailable {

	public ASTAtIsUnavailable(final AtFormulaParserImpl p, final int id) {
		super(p, id);
	}

	@Override
	public ValueHolder evaluate(final FormulaContext ctx) throws FormulaReturnException {
		return checkAvailable(ctx) ? ctx.FALSE : ctx.TRUE;
	}
}
/* JavaCC - OriginalChecksum=f3b6fabf50caf0edf2cf32de73733c67 (do not edit this line) */
