/* Generated By:JJTree: Do not edit this line. ASTUserDefinedFunctionParameter.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package org.openntf.domino.formula.ast;

import org.openntf.domino.formula.FormulaContext;
import org.openntf.domino.formula.FormulaReturnException;
import org.openntf.domino.formula.ValueHolder;
import org.openntf.domino.formula.parse.AtFormulaParserImpl;

public class ASTUserDefinedFunctionParameter extends SimpleNode {
	String paramName;

	public ASTUserDefinedFunctionParameter(final AtFormulaParserImpl p, final int id) {
		super(p, id);
	}

	@Override
	public ValueHolder evaluate(final FormulaContext ctx) throws FormulaReturnException {
		return children[0].evaluate(ctx);

	}

	public void init(final String image) {
		paramName = image.toLowerCase();
	}

	public boolean isOptional() {
		return jjtGetNumChildren() == 1;
	}

	public String getNameLC() {
		return paramName;
	}
}
/* JavaCC - OriginalChecksum=16378a4050db5050b35aed3e72d20156 (do not edit this line) */
