/* Generated By:JJTree: Do not edit this line. ASTGetVariable.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
/*
 * © Copyright FOCONIS AG, 2014
 * 
 * Licensed under the Apache License, Version 2.0 (the "License"); 
 * you may not use this file except in compliance with the License. 
 * You may obtain a copy of the License at:
 * 
 * http://www.apache.org/licenses/LICENSE-2.0
 * 
 * Unless required by applicable law or agreed to in writing, software 
 * distributed under the License is distributed on an "AS IS" BASIS, 
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or 
 * implied. See the License for the specific language governing 
 * permissions and limitations under the License.
 */
package org.openntf.domino.formula.parse;

import org.openntf.domino.tests.rpr.formula.eval.FormulaContext;
import org.openntf.domino.tests.rpr.formula.eval.ValueHolder;

public class ASTGetVariable extends SimpleNode {
	private String variableName = "";

	public ASTGetVariable(final int id) {
		super(id);
	}

	public ASTGetVariable(final AtFormulaParser p, final int id) {
		super(p, id);
	}

	public void init(final String image) {
		variableName = image;
	}

	@Override
	public String toString() {
		return super.toString() + ": " + variableName;
	}

	@Override
	public ValueHolder evaluate(final FormulaContext ctx) {
		return ctx.getVar(variableName);
	}

	public void toFormula(final StringBuilder sb) {
		sb.append(variableName);
	}
}
/* JavaCC - OriginalChecksum=6fc7ffc46fcd95aa653ad69d15d081cc (do not edit this line) */
