/* Generated By:JavaCC: Do not edit this line. AtFormulaParserTreeConstants.java Version 5.0 */
package org.openntf.domino.formula.parse;

public interface AtFormulaParserTreeConstants
{
  public int JJTATDO = 0;
  public int JJTVOID = 1;
  public int JJTASSIGNMENT = 2;
  public int JJTSELECT = 3;
  public int JJTOPERATOR = 4;
  public int JJTVALUELIST = 5;
  public int JJTSUBSCRIPT = 6;
  public int JJTATDOWHILE = 7;
  public int JJTATFOR = 8;
  public int JJTATIF = 9;
  public int JJTATIFERROR = 10;
  public int JJTATTRANFORM = 11;
  public int JJTFUNCTION = 12;
  public int JJTVALUEDATEORKW = 13;
  public int JJTVALUESTRING = 14;
  public int JJTVALUEDOUBLE = 15;
  public int JJTVALUELONG = 16;
  public int JJTGETVARIABLE = 17;


  public String[] jjtNodeName = {
    "AtDo",
    "void",
    "Assignment",
    "Select",
    "Operator",
    "ValueList",
    "Subscript",
    "AtDoWhile",
    "AtFor",
    "AtIf",
    "AtIfError",
    "AtTranform",
    "Function",
    "ValueDateOrKW",
    "ValueString",
    "ValueDouble",
    "ValueLong",
    "GetVariable",
  };
}
/* JavaCC - OriginalChecksum=3045f282468b9b4fbf236985ab368e85 (do not edit this line) */
